" Basic settings: Ignore vi compatibility, use filetype plugins, syntax
" highlighting and UTF-8.
set nocompatible
filetype plugin on
syntax on
set encoding=utf-8

" Leader character for mappings.
let mapleader=","
let maplocalleader=","

" In the viminfo state file, store file marks and unlimited register contents.
" Search, command line and input history size are defined via 'history'.
" Also, put the viminfo file in ~/.vim, not directly in the home directory.
set viminfo='100,h,f1,n~/.vim/viminfo
set history=100

" Don't litter .swp files all over the place, put them in ~/.vim/swp instead,
" but fall back to "same directory" if that's not possible for some reason.
set directory=~/.vim/swp,.
