"                 _             _
"  ___  ___ _   _( )___  __   _(_)_ __ ___  _ __ ___
" / __|/ __| | | |// __| \ \ / / | '_ ` _ \| '__/ __|
" \__ \ (__| |_| | \__ \  \ V /| | | | | | | | | (__
" |___/\___|\__, | |___/ (_)_/ |_|_| |_| |_|_|  \___|
"           |___/
" Part of my dotfiles: <https://github.com/scy/dotfiles>


" Basic settings: Ignore vi compatibility, use filetype plugins, syntax
" highlighting and UTF-8.
set nocompatible
filetype plugin on
syntax on
set encoding=utf-8

" Disable modelines for security reasons, see CVE-2019-12735 et al.
" They are off by default on Debian, but "set nocompatible" above will have
" turned them on nevertheless.
set nomodeline



" Leader character for mappings.
let mapleader=","
let maplocalleader=","



"     Session / Swap Files / History    /
" _____________________________________/

" In the viminfo state file, store file marks and unlimited register contents.
" Search, command line and input history size are defined via 'history'.
" Also, put the viminfo file in ~/.vim, not directly in the home directory.
" In Neovim, 'viminfo' is an alias to 'shada', but viminfo and ShaDa files are
" incompatible. So on a system running both Vim and Neovim, 'viminfo'/'shada'
" should point to different files.
set viminfo='100,h,f1
if has('nvim')
	set shada+=n~/.vim/shada
else
	set viminfo+=n~/.vim/viminfo
endif
set history=100

" Don't litter .swp files all over the place, put them in ~/.vim/swp instead,
" but fall back to "same directory" if that's not possible for some reason.
set directory=~/.vim/swp,.



"    Visuals    /
" _____________/

" Dark background, duh.
set background=dark

" Show significant whitespace.
if &encoding == 'utf-8'
	set listchars=tab:›·,nbsp:¯,trail:·
else
	set listchars=tab:\|.,nbsp:_,trail:_
endif
set list

" Show line numbers, but no relative ones. That's because I'm using Windows
" console quite a lot, which has slow rendering (compared to e.g. Windows
" Terminal or even Termux), and 'relativenumber' has to redraw the whole
" number column on each line change.
set number norelativenumber
" Make them unobtrusive.
highlight LineNr ctermfg=DarkGray

" Default tab width.
set tabstop=4 shiftwidth=4

" When splitting vertically, split to the right (not to the left). Similarly,
" when splitting horizontally, split below (not to the top).
set splitright splitbelow

" Changing cursors on mode change.
if &term =~ "xterm"
	let &t_SI = "\<Esc>[5 q" " blinking bar
	let &t_SR = "\<Esc>[3 q" " blinking underscore
	let &t_EI = "\<Esc>[1 q" " blinking block
endif



"    netrw    /
" ___________/

" Disable the banner.
let g:netrw_banner = 0
" When selecting a file, open it in the previous window (or create a new one).
let g:netrw_browse_split = 4
" Show files as a tree by default.
let g:netrw_liststyle = 3
" Default size of the split explorer is 20%.
let g:netrw_winsize = 20



"    Vimwiki    /
" _____________/

" Disable creation of ”temporary wikis“ for every .md file I edit.
let g:vimwiki_global_ext = 0
" When creating a link in a Markdown file, add the `.md` extension.
let g:vimwiki_markdown_link_ext = 1
" List of my personal wikis.
let g:vimwiki_list = [{
	\ 'path': '~/my/w',
	\ 'syntax': 'markdown',
	\ 'ext': '.md',
\ }, {
	\ 'path': '~/my/todo',
	\ 'syntax': 'markdown',
	\ 'ext': '.md',
\ }]



"    Mappings    /
" ______________/

" Toggle file tree.
map <Leader>l :Lexplore<CR>
" Show/hide line numbers.
function! ToggleLineNumbers()
	if &number
		set nonumber norelativenumber
	else
		set number relativenumber
	endif
endfunction
noremap <Leader>n :call ToggleLineNumbers()<CR>
" Toggle between relative and absolute line numbers.
noremap <Leader>N :set relativenumber!<CR>
" Open a terminal window shell that closes automatically when exiting.
map <Leader>! :terminal ++close<CR>
